provider: "openai"

api_keys:
  openai: ""

models:
  openai:
    default: "gpt-3.5-turbo"
    gpt-4o: "gpt-4o"
    o3-mini: "o3-mini"
    o1-preview: "o1-preview"


prompts:
  evaluator_human: "prompts/evaluator_human_prompt.txt"
  evaluator_llm: "prompts/evaluator_llm_prompt.txt"