provider: "openai"

api_keys:
  openai: ""

models:
  openai:
    default: "gpt-3.5-turbo"
    gpt-4o: "gpt-4o"
    o3-mini: "o3-mini"
    o1-preview: "o1-preview"

prompts:
  evaluator_human: "prompts/evaluator_human_prompt.txt"
  evaluator_llm: "prompts/evaluator_llm_prompt.txt"
  decomposition_auto: "prompts/decomposition_prompt_auto.txt"
  decomposition_user: "prompts/decomposition_prompt_user.txt"

database:
  url: "mongodb+srv://{user}:{pass}@dp-database.fczwf.mongodb.net/?retryWrites=true&w=majority&appName=DP-Database"
  database_name: "dp_database"