provider: "openai"

auth_secret_key: "VQ2MfKMyZH5yFRXwluE5WTRZhvP24BD1"

api_keys:
  openai: "api_key1"
  claude: "api_key2"

models:
  openai:
    gpt-3.5-turbo: "gpt-3.5-turbo"
    gpt-4o: "gpt-4o"
    gpt-4o-mini: "gpt-4o-mini"
    o3-mini: "o3-mini"
  claude:
    claude-3-haiku-20240307: "claude-3-haiku-20240307"
    claude_2.1: "claude-2.1"
    claude-3-5-haiku-latest: "claude-3-5-haiku-latest"
    claude-3-7-sonnet-latest: "claude-3-7-sonnet-latest"

prompts:
  evaluator_human: "prompts/evaluator_human_prompt.txt"
  evaluator_llm: "prompts/evaluator_llm_prompt.txt"
  key_extraction: "prompts/extractor_key_elements.txt"
  CoT: "prompts/CoT_prompt.txt"
  SC: "prompts/SC_prompt.txt"
  CoD: "prompts/CoD_prompt.txt"
  PC: "prompts/PC_prompt.txt"
  ReAct: "prompts/ReAct_prompt.txt"
  SC_ReAct: "prompts/SC_React_prompt.txt"
  expert_finder: "prompts/expert_finder_prompt.txt"

database:
  uri: "mongodb+srv://{user}:{pass}@dp-database.fczwf.mongodb.net/?retryWrites=true&w=majority&appName=DP-Database"
  database_name: "dp_database"